name = "filehandling"
uuid = "4b8ed5e0-8069-11e8-094b-3f5425e6acdd"
authors = ["Peter Br√§uer <pb866@york.ac.uk>"]
julia = "0.7-"
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
